# --- General options --- #
title: EULex.NET
description: Cross platform, open source .NET library to access EU legal data
url: https://eulex.net

repository: EULexNET/EULex.NET

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About: "about"
  Download: "download"
  Documentation: "documentation"
  Contribute: "contribute"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/images/eulex-icon-white.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Bertrand Lorentz
  email: "bertrand.lorentz@gmail.com"
  github: EULexNET
  twitter: bl8
  mastodon: oc.todon.fr/@bl8

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: false
  github: true
  twitter: true
  mastodon: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "EULex.NET"

# --- Misc --- #

# Output options (more information on Jekyll's site)
permalink: pretty

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
